### ISSUE TITLE
Unhandled Error: no suitable image found

### ISSUE THREAD

**Issue by sneljo1** [MarshallOfSound/electron-media-service#1]
I do not own a mac myself, but someone encountered this error when launching my app on mac.
The app is not signed and was compiled using electron-builder docker wine into a zip for mac. Is this happening because it was not compiled on a mac/xcode machine?

```Unhandled Error
Error: dlopen(/var/folders/5m/34hcxxwx7tngbg42ydwwf2580000gn/T/.be.sneljo.auryo.bZxKYc, 1): no suitable image found.  Did find:
	/var/folders/5m/34hcxxwx7tngbg42ydwwf2580000gn/T/.be.sneljo.auryo.bZxKYc: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at bindings (/private/var/folders/5m/34hcxxwx7tngbg42ydwwf2580000gn/T/AppTranslocation/690044B8-9D8E-440E-85E9-3A440EA65A9D/d/Auryo.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/private/var/folders/5m/34hcxxwx7tngbg42ydwwf2580000gn/T/AppTranslocation/690044B8-9D8E-440E-85E9-3A440EA65A9D/d/Auryo.app/Contents/Resources/app.asar/node_modules/electron-media-service/src/darwin/index.js:1:206)
    at Object.<anonymous> (/private/var/folders/5m/34hcxxwx7tngbg42ydwwf2580000gn/T/AppTranslocation/690044B8-9D8E-440E-85E9-3A440EA65A9D/d/Auryo.app/Contents/Resources/app.asar/node_modules/electron-media-service/src/darwin/index.js:61:3)
    at Object.<anonymous> (/private/var/folders/5m/34hcxxwx7tngbg42ydwwf2580000gn/T/AppTranslocation/690044B8-9D8E-440E-85E9-3A440EA65A9D/d/Auryo.app/Contents/Resources/app.asar/node_modules/electron-media-service/src/index.js:9:24)
    at Object.<anonymous> (/private/var/folders/5m/34hcxxwx7tngbg42ydwwf2580000gn/T/AppTranslocation/690044B8-9D8E-440E-85E9-3A440EA65A9D/d/Auryo.app/Contents/Resources/app.asar/node_modules/electron-media-service/src/index.js:18:3)
    at Object.electron-media-service (/private/var/folders/5m/34hcxxwx7tngbg42ydwwf2580000gn/T/AppTranslocation/690044B8-9D8E-440E-85E9-3A440EA65A9D/d/Auryo.app/Contents/Resources/app.asar/main.js:1:334602)
    at M (/private/var/folders/5m/34hcxxwx7tngbg42ydwwf2580000gn/T/AppTranslocation/690044B8-9D8E-440E-85E9-3A440EA65A9D/d/Auryo.app/Contents/Resources/app.asar/main.js:1:538)
    at Q.register (/private/var/folders/5m/34hcxxwx7tngbg42ydwwf2580000gn/T/AppTranslocation/690044B8-9D8E-440E-85E9-3A440EA65A9D/d/Auryo.app/Contents/Resources/app.asar/main.js:1:20755)
    at ue.filter.forEach (/private/var/folders/5m/34hcxxwx7tngbg42ydwwf2580000gn/T/AppTranslocation/690044B8-9D8E-440E-85E9-3A440EA65A9D/d/Auryo.app/Contents/Resources/app.asar/main.js:1:3467)
    at M.default.start (/private/var/folders/5m/34hcxxwx7tngbg42ydwwf2580000gn/T/AppTranslocation/690044B8-9D8E-440E-85E9-3A440EA65A9D/d/Auryo.app/Contents/Resources/app.asar/main.js:1:3450)
    at App.G.app.on (/private/var/folders/5m/34hcxxwx7tngbg42ydwwf2580000gn/T/AppTranslocation/690044B8-9D8E-440E-85E9-3A440EA65A9D/d/Auryo.app/Contents/Resources/app.asar/main.js:1:5571)```

**Comment by MarshallOfSound** [comment]
@Superjo149 If you want to use this node module it has to be compiled / built on a mac 👍
